version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Supabase Configuration
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL=http://localhost:3000
      
      # Judge0 Configuration (optional)
      - JUDGE0_API_KEY=${JUDGE0_API_KEY}
      - JUDGE0_API_URL=${JUDGE0_API_URL}
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shodh-network

networks:
  shodh-network:
    driver: bridge
